name: Continuous Integration
on:
  push:
    paths-ignore:
      - "README.md"
  pull_request:
    paths-ignore:
      - "README.md"
  
jobs:
  build-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker build --target test --tag todo-app:test .
    - run: docker run todo-app:test
  
  build-prod:
    name: Build the production image
    if: ${{ github.ref == 'refs/heads/exercise-9' }}
    needs: build-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker build --target production --tag todo-app:prod .
      working-directory: .

  deploy:
    name: Deploy to Dockerhub and Azure
    if: ${{ github.ref == 'refs/heads/exercise-9' }}
    runs-on: ubuntu-latest
    needs: build-prod
    steps:
    - run: echo "Deploying to production server on branch $GITHUB_REF"

    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Publish the Dockerfile
      run: docker push redbluesquare/todo-app:prod

    - name: deploy to Azure using the webhook
      run: curl -dH -X POST ${{ secrets.AZURE_TODOAPP_WEBHOOK }}